/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

import SoftGira.EnviarCorreo;

/**
 *
 * @author mendez
 */
public class Soporte extends javax.swing.JPanel {

    /**
     * Creates new form Soporte
     */
    public Soporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAsunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbPrioridad = new javax.swing.JComboBox<>();
        Enviar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Manual = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 34, 111));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOPORTE TECNICO  |  SOFT-GIRA");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 15, 1));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 34, 111));
        jLabel2.setText("Reportar  de  Falla");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 34, 111));
        jLabel3.setText("Asunto:");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 34, 111));
        jLabel4.setText("Descripción del error:");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 34, 111));
        jLabel5.setText("Prioridad");

        cbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Normal", "Alta", "Urgente" }));

        Enviar.setBackground(new java.awt.Color(31, 34, 111));
        Enviar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Enviar.setForeground(new java.awt.Color(255, 255, 255));
        Enviar.setText("ENVIAR");
        Enviar.addActionListener(this::EnviarActionPerformed);

        jPanel2.setBackground(new java.awt.Color(240, 240, 240));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 34, 111));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CONTACTO:");

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 34, 111));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("soperte_LUMMEN@gmail.com");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 34, 111));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VERSION 1.0");

        Manual.setBackground(new java.awt.Color(31, 34, 111));
        Manual.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        Manual.setForeground(new java.awt.Color(255, 255, 255));
        Manual.setText("MANUAL");
        Manual.addActionListener(this::ManualActionPerformed);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mesa-de-ayuda (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(Manual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(73, 73, 73)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(Manual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtAsunto)
                    .addComponent(jLabel4)
                    .addComponent(txtDescripcion)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
                                           
    // 1. Obtener el texto de tus campos
    String asunto = txtAsunto.getText().trim();
    String descripcion = txtDescripcion.getText().trim();
    String prioridad = cbPrioridad.getSelectedItem() != null ? cbPrioridad.getSelectedItem().toString() : "Normal";

    // 2. Validar que no envíen campos vacíos
    if (asunto.isEmpty() || descripcion.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, completa el asunto y la descripción del error.", 
            "Campos Incompletos", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 3. Cambiar el cursor a 'cargando' mientras se envía el correo
    this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

    // 4. Llamar a la clase que creamos
    boolean enviado = EnviarCorreo.enviarReporte(asunto, descripcion, prioridad);

    // 5. Regresar el cursor a la normalidad
    this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    // 6. Verificar el resultado del envío
    if (enviado) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "¡El reporte fue enviado con éxito al equipo de soporte!", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos
        txtAsunto.setText("");
        txtDescripcion.setText("");
        cbPrioridad.setSelectedIndex(0);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "No se pudo enviar el reporte.\nRevisa tu conexión a internet o la configuración del correo.", 
            "Error al Enviar", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }    }//GEN-LAST:event_EnviarActionPerformed

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed
try {
        java.io.InputStream stream = getClass().getResourceAsStream("/Manual/Manual_Usuario.pdf");
        
        if (stream != null) {
            java.io.File tempFile = java.io.File.createTempFile("Manual_SOFT_GIRA_", ".pdf");
            tempFile.deleteOnExit();
            
            java.nio.file.Files.copy(stream, tempFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);

            // Detectamos el Sistema Operativo
            String os = System.getProperty("os.name").toLowerCase();

            if (os.contains("win")) {
                // Comando nativo para abrir archivos en Windows
                new ProcessBuilder("cmd", "/c", "start", "", tempFile.getAbsolutePath()).start();
            } else if (os.contains("mac")) {
                // Comando nativo para macOS
                new ProcessBuilder("open", tempFile.getAbsolutePath()).start();
            } else {
                // Comando nativo para Linux
                new ProcessBuilder("xdg-open", tempFile.getAbsolutePath()).start();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No se encontró el manual dentro del sistema.", 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al abrir el PDF: " + ex.getMessage());
}    }//GEN-LAST:event_ManualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JButton Manual;
    private javax.swing.JComboBox<String> cbPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAsunto;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
