/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

import MODELO.ConexionBD;
import javax.swing.JButton;
import VISTA.PRINCIPAL;
import java.awt.event.MouseAdapter;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author mendez
 */
public class Corte_Caja extends javax.swing.JDialog {
private PRINCIPAL principal;

public Corte_Caja(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    
    initComponents();
    
    txtRetiros.setText("0");
    inicializarCorte();
    
    this.setSize(990, 600); // 1. Primero establecemos el tamaño
    this.setResizable(false);
    
    // 2. DESPUÉS la centramos respecto a la ventana principal para que aparezca en su lugar correcto
    this.setLocationRelativeTo(parent); 
}
    public Corte_Caja() {
        initComponents();
        txtRetiros.setText("0");
        inicializarCorte();
    }

    private void inicializarCorte() {
       // ¡AQUÍ RECUPERAMOS LOS DATOS!
        if (VISTA.PRINCIPAL.cajaAbierta) {
            jTextField1.setText(String.valueOf(VISTA.PRINCIPAL.fondoInicialGuardado));
            jTextField1.setEnabled(false);
            jButton1.setEnabled(false); // Tu botón de Inicio de corte
        }

        // Calculamos los totales inmediatamente al abrir la vista
        calcularTotalesCorte(); 
    }

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblVentasEfectivo = new javax.swing.JLabel();
        txtRetiros = new javax.swing.JTextField();
        lblVentasTarjetas = new javax.swing.JLabel();
        lblTotalVentaDia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblSub500 = new javax.swing.JLabel();
        lblSub200 = new javax.swing.JLabel();
        lblSub100 = new javax.swing.JLabel();
        lblSub50 = new javax.swing.JLabel();
        lblSub20 = new javax.swing.JLabel();
        lblSub10 = new javax.swing.JLabel();
        lblSub5 = new javax.swing.JLabel();
        lblSub2 = new javax.swing.JLabel();
        lblSub1 = new javax.swing.JLabel();
        lblTotalContado = new javax.swing.JLabel();
        lblDiferencia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Corte de caja");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(31, 34, 111));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("IMPRIMIR CORTE");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 140, 50));

        jButton3.setBackground(new java.awt.Color(31, 34, 111));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("FINALIZAR CORTE");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 150, 50));

        jButton1.setBackground(new java.awt.Color(31, 34, 111));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIO DE CORTE");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 140, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 34, 111));
        jLabel3.setText("FONDO INICIAL");

        jTextField1.setPreferredSize(new java.awt.Dimension(110, 32));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 34, 111));
        jLabel4.setText("VENTAS EN EFECTIVO");

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 34, 111));
        jLabel5.setText("RETIROS  /  ENTREGAS");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 34, 111));
        jLabel6.setText("VENTAS EN TARGETAS");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 34, 111));
        jLabel7.setText("TOTAL DE VENTA DE DIA");

        txtRetiros.setMinimumSize(new java.awt.Dimension(110, 32));
        txtRetiros.setPreferredSize(new java.awt.Dimension(110, 32));
        txtRetiros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRetirosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalVentaDia, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVentasEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVentasTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblVentasEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRetiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalVentaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(lblVentasTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 440, 390));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 34, 111));
        jLabel8.setText("DOMINACION");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(31, 34, 111));
        jLabel9.setText("CANTIDAD");

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(31, 34, 111));
        jLabel10.setText("SUBTOTAL");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(31, 34, 111));
        jLabel11.setText("BILLETES $200");

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(31, 34, 111));
        jLabel12.setText("BILLETES $500");

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(31, 34, 111));
        jLabel13.setText("BILLETES $100");

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(31, 34, 111));
        jLabel14.setText("BILLETES $50");

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(31, 34, 111));
        jLabel15.setText("BILLETES $20");

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(31, 34, 111));
        jLabel16.setText("MONEDAS  $10");

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(31, 34, 111));
        jLabel17.setText("MONEDAS $5");

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(31, 34, 111));
        jLabel18.setText("MONEDAS $2");

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(31, 34, 111));
        jLabel19.setText("MONEDAS  $1");

        jTextField2.setText("0");
        jTextField2.setMinimumSize(new java.awt.Dimension(10, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 30));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jTextField3.setText("0");
        jTextField3.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jTextField4.setText("0");
        jTextField4.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField5.setText("0");
        jTextField5.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jTextField6.setText("0");
        jTextField6.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jTextField7.setText("0");
        jTextField7.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        jTextField8.setText("0");
        jTextField8.setMinimumSize(new java.awt.Dimension(100, 30));
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jTextField9.setText("0");
        jTextField9.setMinimumSize(new java.awt.Dimension(100, 24));
        jTextField9.setPreferredSize(new java.awt.Dimension(100, 30));
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jTextField10.setText("0");
        jTextField10.setMinimumSize(new java.awt.Dimension(100, 24));
        jTextField10.setPreferredSize(new java.awt.Dimension(100, 25));
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(31, 34, 111));
        jLabel20.setText("TOTAL CONTADO");

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(31, 34, 111));
        jLabel21.setText("DIFERENCIA EN EFECTIVO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel19)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTotalContado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSub100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSub50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSub200)
                                    .addComponent(lblSub5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSub10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSub20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSub500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSub500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblSub200)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSub100, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSub50, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(lblSub20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(lblSub10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSub5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTotalContado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(lblDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel20))
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 34, 111));
        jLabel1.setText("2. CONTENO FISICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 34, 111));
        jLabel2.setText("1.  REGISTRO DEL SISTEMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_jTextField2KeyReleased

    private void txtRetirosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirosKeyReleased
        calcularTotalesCorte();
    }//GEN-LAST:event_txtRetirosKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    // 1. Obtención y validación del monto inicial de forma segura
    double fondo = parsearDobleSafe(jTextField1.getText());
    if (fondo <= 0) {
        JOptionPane.showMessageDialog(this, "Ingrese un fondo inicial válido.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Obtener el ID del usuario desde la sesión global
    int idUsuario = MODELO.SesionActual.idUsuarioLogueado;
    CONTROLADOR.CorteCajaDao corteDao = new CONTROLADOR.CorteCajaDao();

    // 3. Verificar si el usuario ya tiene un corte abierto en BD
    if (corteDao.hayCorteAbierto(idUsuario)) {
        JOptionPane.showMessageDialog(this, "Ya existe un corte de caja abierto para este usuario.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 4. Insertar el inicio de corte en la Base de Datos
    boolean inicioCorrecto = corteDao.abrirCorte(idUsuario, fondo);

    if (inicioCorrecto) {
        // Actualizamos estado en la interfaz
        VISTA.PRINCIPAL.fondoInicialGuardado = fondo;
        VISTA.PRINCIPAL.cajaAbierta = true;

        jTextField1.setEnabled(false);
        jButton1.setEnabled(false);

        JOptionPane.showMessageDialog(this, "Corte de caja iniciado correctamente.");
        calcularTotalesCorte();

        // =========================================================================
        // 5. MSTRAR PUNTO DE VENTA EN LA VENTANA PRINCIPAL
        // =========================================================================
        for (java.awt.Frame frame : java.awt.Frame.getFrames()) {
            if (frame instanceof VISTA.PRINCIPAL) {
                ((VISTA.PRINCIPAL) frame).mostrarPanel(new VISTA.Punto_Venta());
                break;
            }
        }

        // =========================================================================
        // 6. OCULTAR Y CERRAR LA VENTANA EMERGENTE (JDialog de Corte)
        // =========================================================================
        java.awt.Window ventanaFlotante = javax.swing.SwingUtilities.getWindowAncestor(this);

        if (ventanaFlotante != null && !(ventanaFlotante instanceof VISTA.PRINCIPAL)) {
            ventanaFlotante.setVisible(false); // Ocualta la ventana emergente de inmediato
            ventanaFlotante.dispose();        // Libera los recursos de la ventana
        }

    } else {
        JOptionPane.showMessageDialog(this, "No se pudo registrar el inicio de caja en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al iniciar el corte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
    // 1. OBTENER LOS VALORES DE LA VISTA
    double fondoInicial = parsearDoble(jTextField1.getText());
    double ventasEfectivo = parsearDoble(lblVentasEfectivo.getText());
    double ventasTarjeta = parsearDoble(lblVentasTarjetas.getText());
    double totalVentasGeneral = ventasEfectivo + ventasTarjeta;
    double retiros = parsearDoble(txtRetiros.getText());

    double efectivoEsperado = fondoInicial + ventasEfectivo - retiros;
    double efectivoEnCaja = parsearDoble(lblTotalContado.getText());
    double diferencia = efectivoEnCaja - efectivoEsperado;

    // --- CAMBIO CLAVE 1: Obtener ID dinámico del usuario logueado ---
    int idUsuario = MODELO.SesionActual.idUsuarioLogueado;

    // 2. UTILIZAR EL DAO (usando los métodos unificados que gestionan la conexión automáticamante)
    CONTROLADOR.CorteCajaDao corteDao = new CONTROLADOR.CorteCajaDao();
    int idCorteAbierto = corteDao.obtenerIdCorteAbierto(idUsuario);

    // Validar si realmente hay un corte abierto para cerrar
    if (idCorteAbierto == -1) {
        JOptionPane.showMessageDialog(this, "No se encontró ningún corte abierto para este usuario.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Cerrar el corte en la base de datos
    boolean cerradoConExito = corteDao.cerrarCaja(idCorteAbierto, idUsuario, efectivoEnCaja);

    if (!cerradoConExito) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al intentar cerrar el corte en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3. MENSAJE DE ÉXITO
    JOptionPane.showMessageDialog(
            this,
            "¡Corte de caja guardado correctamente en MySQL!\n\n"
            + "Total ventas: $" + String.format("%.2f", totalVentasGeneral)
            + "\nEfectivo esperado: $" + String.format("%.2f", efectivoEsperado)
            + "\nEfectivo contado: $" + String.format("%.2f", efectivoEnCaja)
            + "\nDiferencia: $" + String.format("%.2f", diferencia),
            "Corte Finalizado",
            JOptionPane.INFORMATION_MESSAGE
    );

    // 4. LIMPIAR PANTALLA Y REINICIAR CAJA
    jTextField1.setText("0");
    txtRetiros.setText("0");
    // ... (tus limpiezas de textfields adicionales) ...

    VISTA.PRINCIPAL.cajaAbierta = false;
    VISTA.PRINCIPAL.fondoInicialGuardado = 0.0;

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al finalizar el corte:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
    // =========================================================================
    // 1. OBTENER Y SANITIZAR VALORES DE LA PANTALLA
    // =========================================================================
    double fondoInicial = parsearDobleSafe(jTextField1.getText());
    double ventasEfectivo = parsearDobleSafe(lblVentasEfectivo.getText());
    double ventasTarjeta = parsearDobleSafe(lblVentasTarjetas.getText());
    double retiros = parsearDobleSafe(txtRetiros.getText());
    double totalContado = parsearDobleSafe(lblTotalContado.getText());
    double diferencia = parsearDobleSafe(lblDiferencia.getText());
    double totalEsperado = fondoInicial + ventasEfectivo - retiros;

    int idUsuario = MODELO.SesionActual.idUsuarioLogueado;

    // =========================================================================
    // 2. REGISTRAR CIERRE EN BASE DE DATOS (Primero la persistencia)
    // =========================================================================
    CONTROLADOR.CorteCajaDao corteDao = new CONTROLADOR.CorteCajaDao();
    int idCorteAbierto = corteDao.obtenerIdCorteAbierto(idUsuario);

    if (idCorteAbierto == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "No se encontró ningún corte abierto en la base de datos para este usuario.", 
            "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean cerradoEnBD = corteDao.cerrarCaja(idCorteAbierto, idUsuario, totalContado);

    if (!cerradoEnBD) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Ocurrió un error al intentar guardar el cierre en la base de datos.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // =========================================================================
    // 3. CONSTRUCCIÓN DEL TICKET E IMPRESIÓN
    // =========================================================================
    try {
        Runtime.getRuntime().exec("cancel -a Ticketera");
    } catch (Exception ex) {
        // Ignorar si no existe el comando en el SO
    }

    StringBuilder ticket = new StringBuilder();
    ticket.append("\n");
    ticket.append("================================\n");
    ticket.append("    LUMMEL SYSTEM INTEGRATION   \n");
    ticket.append("      REPORTE DE CORTE DE CAJA  \n");
    ticket.append("================================\n");
    ticket.append("Fecha: ").append(java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("\n");
    ticket.append("Cajero ID: ").append(idUsuario).append("\n");
    ticket.append("--------------------------------\n");
    
    ticket.append(String.format("Fondo Inicial:     $%10.2f\n", fondoInicial));
    ticket.append(String.format("Ventas Efectivo:   $%10.2f\n", ventasEfectivo));
    ticket.append(String.format("Ventas Tarjeta:    $%10.2f\n", ventasTarjeta));
    ticket.append(String.format("Retiros / Entregas:$%10.2f\n", retiros));
    ticket.append("--------------------------------\n");
    ticket.append(String.format("Total Esperado:    $%10.2f\n", totalEsperado));
    ticket.append(String.format("Total Contado:     $%10.2f\n", totalContado));
    ticket.append("--------------------------------\n");
    ticket.append(String.format("Diferencia:        $%10.2f\n", diferencia));
    ticket.append("================================\n");
    ticket.append("   ¡CORTE GENERADO CON ÉXITO!   \n");
    ticket.append("\n\n\n\n");
    
    // Comando ESC/POS para corte de papel automático en térmicas (GS V 66 0)
    ticket.append((char) 29).append((char) 86).append((char) 66).append((char) 0);

    javax.print.PrintService[] servicios = javax.print.PrintServiceLookup.lookupPrintServices(null, null);
    javax.print.PrintService impresoraTicketera = null;

    for (javax.print.PrintService servicio : servicios) {
        if (servicio.getName().equalsIgnoreCase("Ticketera")) {
            impresoraTicketera = servicio;
            break;
        }
    }

    if (impresoraTicketera != null) {
        javax.print.DocPrintJob trabajo = impresoraTicketera.createPrintJob();
        byte[] bytesTicket = ticket.toString().getBytes("ISO-8859-1");
        javax.print.Doc doc = new javax.print.SimpleDoc(bytesTicket, javax.print.DocFlavor.BYTE_ARRAY.AUTOSENSE, null);
        trabajo.print(doc, null);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El corte se guardó en BD, pero no se encontró la impresora 'Ticketera'.", 
            "Advertencia de Impresión", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    // =========================================================================
    // 4. REINICIAR Y LIMPIAR INTERFAZ
    // =========================================================================
    jTextField1.setText("0");
    txtRetiros.setText("0");

    jTextField2.setText("0");
    jTextField3.setText("0");
    jTextField4.setText("0");
    jTextField5.setText("0");
    jTextField6.setText("0");
    jTextField7.setText("0");
    jTextField8.setText("0");
    jTextField9.setText("0");
    jTextField10.setText("0");

    lblVentasEfectivo.setText("0.00");
    lblVentasTarjetas.setText("0.00");
    lblTotalVentaDia.setText("0.00");
    lblTotalContado.setText("0.00");
    lblDiferencia.setText("0.00");

    if (lblSub500 != null) lblSub500.setText("");
    if (lblSub200 != null) lblSub200.setText("");
    if (lblSub100 != null) lblSub100.setText("");
    if (lblSub50 != null) lblSub50.setText("");
    if (lblSub20 != null) lblSub20.setText("");
    if (lblSub10 != null) lblSub10.setText("");
    if (lblSub5 != null) lblSub5.setText("");
    if (lblSub2 != null) lblSub2.setText("");
    if (lblSub1 != null) lblSub1.setText("");

    jTextField1.setEnabled(true);
    jTextField1.setEditable(true);
    jButton1.setEnabled(true);

    VISTA.PRINCIPAL.cajaAbierta = false;
    VISTA.PRINCIPAL.fondoInicialGuardado = 0.0;

    try {
        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (ventana instanceof VISTA.PRINCIPAL) {
            ((VISTA.PRINCIPAL) ventana).bloquearMenuLateral(false);
        }
    } catch (Exception ex) {
        // Excepción de UI ignorada si aplica
    }

    javax.swing.JOptionPane.showMessageDialog(this,
        "¡Corte guardado en Base de Datos y ticket finalizado correctamente!",
        "Corte Completo",
        javax.swing.JOptionPane.INFORMATION_MESSAGE);

    jTextField1.requestFocus();
    jTextField1.selectAll();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Error al finalizar el corte: " + e.getMessage(), 
        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }
private double parsearDobleSafe(String texto) {
    if (texto == null) return 0.0;
    String limpio = texto.replaceAll("[^0-9.-]", "").trim();
    if (limpio.isEmpty() || limpio.equals("-")) return 0.0;
    try {
        return Double.parseDouble(limpio);
    } catch (NumberFormatException e) {
        return 0.0;
    }

    }//GEN-LAST:event_jButton2ActionPerformed
// --- MÉTODO PARA ESCUCHAR CUANDO EL USUARIO ESCRIBE ---
// --- MÉTODO PARA CALCULAR LOS TOTALES DEL CORTE ---
    private void calcularTotalesCorte() {
       try {
            // --- 1. REGISTRO DEL SISTEMA ---
            double fondoInicial = VISTA.PRINCIPAL.cajaAbierta ?  
                                  VISTA.PRINCIPAL.fondoInicialGuardado :  
                                  parseDouble(jTextField1.getText());

            // A. Ventas del sistema (vienen automáticas desde el Punto de Venta)
            double ventasEfectivo = VISTA.PRINCIPAL.ventasEfectivoDia; 
            double ventasTarjeta  = VISTA.PRINCIPAL.ventasTarjetaDia;
            
            // B. Retiros (leído directamente del JTextField que escribe el usuario)
            double retiros = parsearDoble(txtRetiros.getText()); 

            // C. Total general vendido en el día
            double totalVentaDia = ventasEfectivo + ventasTarjeta;

            // D. LO QUE DEBE HABER FÍSICAMENTE EN CAJA = (Fondo Inicial + Ventas Efectivo) - Retiros
            double totalEsperadoEfectivo = (fondoInicial + ventasEfectivo) - retiros;

            // --- 2. MOSTRAR DATOS EN LA IZQUIERDA ---
            lblVentasEfectivo.setText(String.format("$%.2f", ventasEfectivo));
            lblVentasTarjetas.setText(String.format("$%.2f", ventasTarjeta));
            lblTotalVentaDia.setText(String.format("$%.2f", totalVentaDia));

            // --- 3. CONTEO FÍSICO (DESGLOSE DE BILLETES) ---
            int cant500 = parsearEntero(jTextField2.getText());
            int cant200 = parsearEntero(jTextField3.getText());
            int cant100 = parsearEntero(jTextField4.getText());
            int cant50  = parsearEntero(jTextField5.getText());
            int cant20  = parsearEntero(jTextField6.getText());
            int cant10  = parsearEntero(jTextField7.getText());
            int cant5   = parsearEntero(jTextField8.getText());
            int cant2   = parsearEntero(jTextField9.getText());
            int cant1   = parsearEntero(jTextField10.getText());

            double sub500 = cant500 * 500.0;
            double sub200 = cant200 * 200.0;
            double sub100 = cant100 * 100.0;
            double sub50  = cant50  * 50.0;
            double sub20  = cant20  * 20.0;
            double sub10  = cant10  * 10.0;
            double sub5   = cant5   * 5.0;
            double sub2   = cant2   * 2.0;
            double sub1   = cant1   * 1.0;

            lblSub500.setText(String.format("$%.2f", sub500));
            lblSub200.setText(String.format("$%.2f", sub200));
            lblSub100.setText(String.format("$%.2f", sub100));
            lblSub50.setText(String.format("$%.2f", sub50));
            lblSub20.setText(String.format("$%.2f", sub20));
            lblSub10.setText(String.format("$%.2f", sub10));
            lblSub5.setText(String.format("$%.2f", sub5));
            lblSub2.setText(String.format("$%.2f", sub2));
            lblSub1.setText(String.format("$%.2f", sub1));

            double totalFisico = sub500 + sub200 + sub100 + sub50 + sub20 + sub10 + sub5 + sub2 + sub1;

            // --- 4. DIFERENCIA REAL EN EFECTIVO ---
            double diferencia = totalFisico - totalEsperadoEfectivo;

            lblTotalContado.setText(String.format("$%.2f", totalFisico));

            if (diferencia == 0) {
                lblDiferencia.setText(" $0.00 (Caja Cuadrada)");
                lblDiferencia.setForeground(new java.awt.Color(0, 150, 0)); // Verde
            } else if (diferencia < 0) {
                lblDiferencia.setText(String.format(" -$%.2f (Faltante)", Math.abs(diferencia)));
                lblDiferencia.setForeground(java.awt.Color.RED); // Rojo
            } else {
                lblDiferencia.setText(String.format(" +$%.2f (Sobrante)", diferencia));
                lblDiferencia.setForeground(new java.awt.Color(200, 120, 0)); // Naranja
            }

        } catch (Exception e) {
            // Manejo silencioso durante edición
        }
    }

    private double parsearDoble(String texto) {
        if (texto == null || texto.trim().isEmpty()) {
            return 0.0;
        }
        try {
            String limpio = texto.replaceAll("[^0-9.]", "").trim();
            return limpio.isEmpty() ? 0.0 : Double.parseDouble(limpio);
        } catch (NumberFormatException e) {
            return 0.0; 
        }
    }

    private int parsearEntero(String texto) {
        if (texto == null || texto.trim().isEmpty()) {
            return 0;
        }
        try {
            String limpio = texto.replaceAll("[^0-9]", "").trim();
            return limpio.isEmpty() ? 0 : Integer.parseInt(limpio);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private boolean guardarCorteEnBD() {

    String sql = "INSERT INTO CorteCaja (" +
                 "id_Usuario, " +
                 "fecha_cierre, " +
                 "fondo_inicial, " +
                 "total_ventas_efectivo, " +
                 "total_ventas_tarjeta, " +
                 "total_ventas_general, " +
                 "total_efectivo_esperado, " +
                 "efectivo_en_caja, " +
                 "diferencia, " +
                 "estatus) " +
                 "VALUES (?, NOW(), ?, ?, ?, ?, ?, ?, ?, 'CERRADO')";

    try (Connection con = ConexionBD.conectar();
         PreparedStatement ps = con.prepareStatement(sql)) {

        if (con == null) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo conectar con la base de datos.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Obtener los valores actuales
        double fondoInicial = parsearDoble(jTextField1.getText());

        double ventasEfectivo = VISTA.PRINCIPAL.ventasEfectivoDia;
        double ventasTarjeta = VISTA.PRINCIPAL.ventasTarjetaDia;

        double totalVentasGeneral = ventasEfectivo + ventasTarjeta;

        double retiros = parsearDoble(txtRetiros.getText());

        double efectivoEsperado =
                (fondoInicial + ventasEfectivo) - retiros;

        // Obtener el efectivo contado físicamente
        int cant500 = parsearEntero(jTextField2.getText());
        int cant200 = parsearEntero(jTextField3.getText());
        int cant100 = parsearEntero(jTextField4.getText());
        int cant50 = parsearEntero(jTextField5.getText());
        int cant20 = parsearEntero(jTextField6.getText());
        int cant10 = parsearEntero(jTextField7.getText());
        int cant5 = parsearEntero(jTextField8.getText());
        int cant2 = parsearEntero(jTextField9.getText());
        int cant1 = parsearEntero(jTextField10.getText());

        double efectivoCaja =
                (cant500 * 500.0) +
                (cant200 * 200.0) +
                (cant100 * 100.0) +
                (cant50 * 50.0) +
                (cant20 * 20.0) +
                (cant10 * 10.0) +
                (cant5 * 5.0) +
                (cant2 * 2.0) +
                (cant1 * 1.0);

        double diferencia = efectivoCaja - efectivoEsperado;

        // ID del usuario
        // CAMBIA ESTE 1 por el ID del usuario que inició sesión
        int idUsuario = 1;

        ps.setInt(1, idUsuario);
        ps.setDouble(2, fondoInicial);
        ps.setDouble(3, ventasEfectivo);
        ps.setDouble(4, ventasTarjeta);
        ps.setDouble(5, totalVentasGeneral);
        ps.setDouble(6, efectivoEsperado);
        ps.setDouble(7, efectivoCaja);
        ps.setDouble(8, diferencia);

        int filas = ps.executeUpdate();

        if (filas > 0) {
            JOptionPane.showMessageDialog(this,
                    "El corte se guardó correctamente en MySQL.",
                    "Corte guardado",
                    JOptionPane.INFORMATION_MESSAGE);
            return true;
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(this,
                "Error al guardar el corte en MySQL:\n" + e.getMessage(),
                "Error SQL",
                JOptionPane.ERROR_MESSAGE);

        e.printStackTrace();
    }

    return false;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblDiferencia;
    private javax.swing.JLabel lblSub1;
    private javax.swing.JLabel lblSub10;
    private javax.swing.JLabel lblSub100;
    private javax.swing.JLabel lblSub2;
    private javax.swing.JLabel lblSub20;
    private javax.swing.JLabel lblSub200;
    private javax.swing.JLabel lblSub5;
    private javax.swing.JLabel lblSub50;
    private javax.swing.JLabel lblSub500;
    private javax.swing.JLabel lblTotalContado;
    private javax.swing.JLabel lblTotalVentaDia;
    private javax.swing.JLabel lblVentasEfectivo;
    private javax.swing.JLabel lblVentasTarjetas;
    private javax.swing.JTextField txtRetiros;
    // End of variables declaration//GEN-END:variables

}
