/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author Luis Angel
 */
public class FINANZAS extends javax.swing.JPanel {

    /**
     * Creates new form FINANZAS
     */
    public FINANZAS() {
        initComponents();
        jDateChooserFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
    @Override
    public void propertyChange(java.beans.PropertyChangeEvent evt) {
        // Detectamos si lo que cambió fue la fecha
        if ("date".equals(evt.getPropertyName())) {
            java.util.Date fechaSeleccionada = (java.util.Date) evt.getNewValue();
            
            if (fechaSeleccionada != null) {
                // Convertimos la fecha al formato de MySQL (YYYY-MM-DD)
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
                String fechaSQL = sdf.format(fechaSeleccionada);
                
                // LLAMAMOS AL CONTROLADOR Y CALCULAMOS EL TOTAL
            CONTROLADOR.ControladorFinanzas controlador = new CONTROLADOR.ControladorFinanzas();
            controlador.buscarVentasPorDia(jTable1, fechaSQL);
            calcularTotalTabla();
            }
            }
        }
     });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTotalAcomulado = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnResumenSemanal = new javax.swing.JButton();
        btnResumenMensual = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(31, 34, 111));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resumen Financiero");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(421, 421, 421)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESUMEN DE INGRESOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 16))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(224, 239, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14))); // NOI18N

        lblTotalAcomulado.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        lblTotalAcomulado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalAcomulado.setText("$0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lblTotalAcomulado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotalAcomulado, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Fecha");

        btnResumenSemanal.setBackground(new java.awt.Color(224, 239, 255));
        btnResumenSemanal.setText("RESUMEN SEMANAL");
        btnResumenSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenSemanalActionPerformed(evt);
            }
        });

        btnResumenMensual.setBackground(new java.awt.Color(224, 239, 255));
        btnResumenMensual.setText("RESUMEN MENSUAL");
        btnResumenMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumenMensualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnResumenSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(btnResumenMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGap(38, 38, 38)
                            .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnResumenSemanal)
                        .addComponent(btnResumenMensual)
                        .addComponent(jLabel2))
                    .addComponent(jDateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResumenSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenSemanalActionPerformed
        // TODO add your handling code here:
        // Creamos un pequeño panel con dos calendarios
    javax.swing.JPanel panelSemanal = new javax.swing.JPanel();
    panelSemanal.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

    com.toedter.calendar.JDateChooser fechaInicio = new com.toedter.calendar.JDateChooser();
    com.toedter.calendar.JDateChooser fechaFin = new com.toedter.calendar.JDateChooser();

    panelSemanal.add(new javax.swing.JLabel("De la fecha:"));
    panelSemanal.add(fechaInicio);
    panelSemanal.add(new javax.swing.JLabel("Hasta la fecha:"));
    panelSemanal.add(fechaFin);

   // Mostramos la ventana emergente
    int opcion = javax.swing.JOptionPane.showConfirmDialog(this, panelSemanal, "Seleccionar Semana / Rango", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

    if (opcion == javax.swing.JOptionPane.OK_OPTION) {
    if (fechaInicio.getDate() != null && fechaFin.getDate() != null) {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String fInicio = sdf.format(fechaInicio.getDate());
    String fFin = sdf.format(fechaFin.getDate());
    
    // LLAMAMOS AL CONTROLADOR Y CALCULAMOS EL TOTAL
    CONTROLADOR.ControladorFinanzas controlador = new CONTROLADOR.ControladorFinanzas();
    controlador.buscarVentasPorRango(jTable1, fInicio, fFin);
    calcularTotalTabla();
    }   else {
    javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar ambas fechas.");
    }
    }
    }//GEN-LAST:event_btnResumenSemanalActionPerformed

    private void btnResumenMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenMensualActionPerformed
        // TODO add your handling code here:
        javax.swing.JPanel panelMensual = new javax.swing.JPanel();
    panelMensual.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

    String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    javax.swing.JComboBox<String> comboMes = new javax.swing.JComboBox<>(meses);

    // JYearChooser también viene en la librería JCalendar
    com.toedter.calendar.JYearChooser comboAnio = new com.toedter.calendar.JYearChooser(); 

    panelMensual.add(new javax.swing.JLabel("Selecciona el Mes:"));
    panelMensual.add(comboMes);
    panelMensual.add(new javax.swing.JLabel("Selecciona el Año:"));
    panelMensual.add(comboAnio);

    int opcion = javax.swing.JOptionPane.showConfirmDialog(this, panelMensual, "Resumen Mensual", javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

    if (opcion == javax.swing.JOptionPane.OK_OPTION) {
    int mesSeleccionado = comboMes.getSelectedIndex() + 1; 
    int anioSeleccionado = comboAnio.getYear();
    
    // LLAMAMOS AL CONTROLADOR Y CALCULAMOS EL TOTAL
    CONTROLADOR.ControladorFinanzas controlador = new CONTROLADOR.ControladorFinanzas();
    controlador.buscarVentasPorMes(jTable1, mesSeleccionado, anioSeleccionado);
    calcularTotalTabla();
    }
    }//GEN-LAST:event_btnResumenMensualActionPerformed

    public void calcularTotalTabla() {
        double totalGeneral = 0.0;
        // Ojo: Asegúrate de que "jTable1" sea el nombre real de tu tabla
        for (int i = 0; i < jTable1.getRowCount(); i++) { 
            Object valor = jTable1.getValueAt(i, 4); // El 4 es la columna "Total"
            if (valor != null) {
                totalGeneral += Double.parseDouble(valor.toString());
            }
        }
        // Ojo: Asegúrate de que "lblTotalAcomulado" sea el nombre real de tu etiqueta de texto
        lblTotalAcomulado.setText(String.format("$%.2f", totalGeneral)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResumenMensual;
    private javax.swing.JButton btnResumenSemanal;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblTotalAcomulado;
    // End of variables declaration//GEN-END:variables
}
