/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Luis Angel
 */
public class PanelUsuarios extends javax.swing.JPanel {

  /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
        configurarAnimaciones(); // Agregamos la llamada aquí
        // 1. Diseño exacto del encabezado de la tabla
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new java.awt.Color(16, 34, 100)); // Fondo Azul Oscuro
        jTable1.getTableHeader().setForeground(java.awt.Color.WHITE); // Letra Blanca
        jTable1.getTableHeader().setFont(new java.awt.Font("Roboto", java.awt.Font.BOLD, 12));
        jTable1.setRowHeight(30); // Filas más anchas para que luzca profesional

        // 2. Renderizador para filas alternadas y selección azul claro
        jTable1.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                // Si la fila está seleccionada, pintarla de azul claro
                if (isSelected) {
                    c.setBackground(new java.awt.Color(173, 216, 230)); // Azul clarito
                    c.setForeground(java.awt.Color.BLACK);
                } else {
                    // Si no está seleccionada, alternar colores (Blanco y Beige muy suave)
                    if (row % 2 == 0) {
                        c.setBackground(java.awt.Color.WHITE);
                    } else {
                        c.setBackground(new java.awt.Color(234, 224, 207)); // Beige de tu paleta
                    }
                    c.setForeground(java.awt.Color.BLACK);
                }
                
                // Centrar el texto en todas las celdas
                setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                return c;
            }
        });

        // ---> AQUÍ DEBES PEGAR EL PASO 4 <---
        // Esto asegura que al cargar la pantalla por primera vez, 
        // se traigan los datos actualizados de la base de datos.
        refrescarTabla(); 
    }
     private void configurarAnimaciones() {
        // Usamos el color azul medio/claro de tu paleta (RGB: 114, 136, 174)
        Color colorHover = new Color(114, 136, 174); 

        // Aplicamos el hover a los paneles que son "opciones" del menú
        configurarHover(jPanel4, colorHover); // Control de Inventarios
        configurarHover(jPanel5, colorHover); // Finanzas
        configurarHover(jPanel6, colorHover); // Compras
        configurarHover(jPanel7, colorHover); // Usuarios
       
     }
      private void configurarHover(JPanel panel, Color colorHover) {
        // Guarda el color original (el gris claro que tienen por defecto)
        Color original = panel.getBackground();
        
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel.setBackground(colorHover); // Cambia al pasar el mouse
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel.setBackground(original); // Regresa al color original al salir
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnDesconectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(249, 250, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 34, 111));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADMINISTRACION DE USUARIOS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(31, 34, 111));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 40, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Usuario Nuevo");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/avatar.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 6, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 70));

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Modificar");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lapiz.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 6, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, 70));

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Eliminar");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/basura.png"))); // NOI18N
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 6, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 70));

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Cambiar Contraseña");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 11));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/llave contrasena.png"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 6, -1, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 150, 70));

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Buscar");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 220, 40));

        btnDesconectar.setBackground(new java.awt.Color(255, 102, 102));
        btnDesconectar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDesconectar.setText("Desbloquear Sesión");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        jPanel3.add(btnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE COMPLETO", "USUARIO", "ROL", "ESTADO", "ULTIMO ACCESO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(235, 235, 235))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      // Buscamos la ventana principal que contiene a este panel
        java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        // Verificamos que la ventana sea tu clase PRINCIPAL
        if (ventana instanceof PRINCIPAL principal) {
            // Le pedimos a la ventana principal que ejecute el método para restaurar el logo
            principal.restaurarVistaLogo();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
         // 1. Instanciamos tu nueva ventana
    VISTA.FrmNuevoUsuario ventanaNuevo = new VISTA.FrmNuevoUsuario();
    ventanaNuevo.setLocationRelativeTo(null); 

    // 2. ¡El Escuchador! Vigila cuándo se cierra la ventana flotante
    ventanaNuevo.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            // Cuando detecta que se cerró (dispose), recarga la tabla sola
            refrescarTabla(); 
        }
    });

    // 3. Finalmente, la mostramos en pantalla
    ventanaNuevo.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        // 1. Pedimos el ID con una ventanita emergente
    String idIngresado = javax.swing.JOptionPane.showInputDialog(this, "Ingresa el ID del usuario a modificar:", "Modificar Usuario", javax.swing.JOptionPane.QUESTION_MESSAGE);
    
    // 2. Si el usuario escribió algo y no le dio a cancelar...
    if (idIngresado != null && !idIngresado.trim().isEmpty()) {
        try {
            int idBuscar = Integer.parseInt(idIngresado.trim()); // Convertimos a número
            
            // 3. Llamamos al controlador para que lo busque en la BD
            CONTROLADOR.ControladorModificarUsuario controlador = new CONTROLADOR.ControladorModificarUsuario();
            String[] datosUsuario = controlador.buscarUsuario(idBuscar);
            
            if (datosUsuario != null) {
                // 4. ¡Sí lo encontró! Abrimos la ventana y le inyectamos los datos
                VISTA.FrmModificarUsuario ventanaModificar = new VISTA.FrmModificarUsuario();
                ventanaModificar.cargarDatos(datosUsuario);
                
                // Hacemos el "truco" para que la tabla se recargue sola al cerrar
                ventanaModificar.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosed(java.awt.event.WindowEvent e) {
                        refrescarTabla(); 
                    }
                });
                
                ventanaModificar.setLocationRelativeTo(null);
                ventanaModificar.setVisible(true);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún usuario con el ID " + idBuscar, "Usuario no encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingresa un número de ID válido (Solo números).", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        // 1. Pedimos el ID con una ventanita
    String idIngresado = javax.swing.JOptionPane.showInputDialog(this, "Ingresa el ID del usuario a ELIMINAR:", "Eliminar Usuario", javax.swing.JOptionPane.QUESTION_MESSAGE);
    
    // 2. Si escribió algo y no canceló
    if (idIngresado != null && !idIngresado.trim().isEmpty()) {
        try {
            int idBuscar = Integer.parseInt(idIngresado.trim()); 
            
            // 3. Llamamos al controlador de eliminación
            CONTROLADOR.ControladorEliminarUsuario controlador = new CONTROLADOR.ControladorEliminarUsuario();
            boolean seElimino = controlador.procesarEliminacion(idBuscar, this);
            
            // 4. Si el controlador dice que sí se borró, actualizamos la tabla solita
            if (seElimino) {
                refrescarTabla(); 
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingresa un número de ID válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        // 1. Pedimos el ID del usuario con una ventana emergente
    String idIngresado = javax.swing.JOptionPane.showInputDialog(this, 
            "Ingrese el ID del usuario que desea cambiar su contraseña:", 
            "Cambiar Contraseña", 
            javax.swing.JOptionPane.QUESTION_MESSAGE);
    
    // 2. Si el usuario escribió algo y no le dio a cancelar...
    if (idIngresado != null && !idIngresado.trim().isEmpty()) {
        try {
            int idBuscar = Integer.parseInt(idIngresado.trim()); // Convertimos a número
            
            // 3. Pedimos la nueva contraseña usando un JPasswordField para que los caracteres se oculten (***)
            javax.swing.JPasswordField txtNuevaContrasena = new javax.swing.JPasswordField();
            Object[] mensaje = {
                "Ingrese la nueva contraseña para el usuario con ID " + idBuscar + ":", txtNuevaContrasena
            };
            
            int opcion = javax.swing.JOptionPane.showConfirmDialog(this, mensaje, "Nueva Contraseña", javax.swing.JOptionPane.OK_CANCEL_OPTION);
            
            // Si le dio a OK en la ventana de la nueva contraseña
            if (opcion == javax.swing.JOptionPane.OK_OPTION) {
                String nuevaPass = new String(txtNuevaContrasena.getPassword());
                
                if (!nuevaPass.trim().isEmpty()) {
                    // 4. Llamamos al controlador para que actualice la base de datos
                    CONTROLADOR.ControladorCambiarContrasena controlador = new CONTROLADOR.ControladorCambiarContrasena();
                    boolean exito = controlador.procesarCambioContrasena(idBuscar, nuevaPass);
                    
                    if (exito) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar. Verifica que el ID exista en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                }
            }
            
        } catch (NumberFormatException e) {
            // Si el usuario metió letras en vez de un número para el ID
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingresa un número de ID válido (Solo números).", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        // 1. Obtenemos el texto que el usuario está escribiendo
    String textoBusqueda = jTextField1.getText();
    
    // Si el texto es el placeholder por defecto "Buscar", no filtramos nada
    if (textoBusqueda.equals("Buscar")) {
        textoBusqueda = "";
    }

    // 2. Obtenemos el modelo actual de la tabla
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    
    // 3. Creamos el ordenador/filtro (TableRowSorter) y se lo asignamos a la tabla
    javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> trs = new javax.swing.table.TableRowSorter<>(modelo);
    jTable1.setRowSorter(trs);
    
    // 4. Aplicamos el filtro
    if (textoBusqueda.trim().length() == 0) {
        trs.setRowFilter(null); // Si no hay texto, mostramos toda la tabla
    } else {
        // "(?i)" hace que la búsqueda ignore mayúsculas y minúsculas.
        // El ", 1" indica que solo buscará coincidencias en la columna "NOMBRE COMPLETO" (índice 1).
        // Si quieres que busque en TODAS las columnas (ID, Usuario, Rol, etc.), simplemente borra el ", 1".
        trs.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + textoBusqueda, 1));
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if (jTextField1.getText().equals("Buscar")) {
        jTextField1.setText("");
        jTextField1.setForeground(new java.awt.Color(0, 0, 0)); // Cambia la letra a negro al escribir
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        if (jTextField1.getText().isEmpty()) {
        jTextField1.setText("Buscar");
        jTextField1.setForeground(new java.awt.Color(204, 204, 204)); // Vuelve al color gris
    }
    }//GEN-LAST:event_jTextField1FocusLost

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:
        // 1. Obtenemos la fila que el administrador seleccionó en la tabla
    int filaSeleccionada = jTable1.getSelectedRow();

    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, selecciona un usuario de la tabla para desconectarlo.", 
            "Aviso", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Extraemos el nombre de usuario (Columna 2) y su estado actual (Columna 4)
    String username = jTable1.getValueAt(filaSeleccionada, 2).toString();
    String estadoActual = jTable1.getValueAt(filaSeleccionada, 4).toString();

    // Validamos si el usuario ya está desconectado para no hacer consultas innecesarias
    if (estadoActual.equalsIgnoreCase("Inactivo")) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "El usuario '" + username + "' ya se encuentra inactivo. No es necesario desconectarlo.", 
            "Aviso", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 3. Pedimos confirmación de seguridad
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de forzar el cierre de sesión del usuario '" + username + "'?\nEsto liberará su cuenta para que pueda volver a entrar.", 
        "Confirmar Desconexión", 
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.WARNING_MESSAGE);

    // 4. Si el administrador confirma, ejecutamos la actualización
    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        
        // Reutilizamos tu modelo existente para apagar la sesión (enviar un 0)
        MODELO.ConsultasUsuario modeloUsuario = new MODELO.ConsultasUsuario();
        boolean exito = modeloUsuario.actualizarEstadoSesion(username, 0);

        if (exito) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "¡La sesión de '" + username + "' ha sido cerrada exitosamente!");
                
            // Recargamos la tabla para que el estado cambie visualmente a "Inactivo"
            refrescarTabla(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Hubo un error al intentar desconectar al usuario en la base de datos.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnDesconectarActionPerformed
    // Método para recargar la tabla cuando queramos
    public void refrescarTabla() {
        CONTROLADOR.ControladorPanelUsuarios controlador = new CONTROLADOR.ControladorPanelUsuarios();
        controlador.llenarTabla(jTable1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
